services:
  - type: web
    name: dost-ai
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.openrouter
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: OPENROUTER_API_KEY
        sync: false  # This will be set manually in Render dashboard 